version: '3'

services:
  api:
    build: .
    depends_on:
      - mysql
    environment:
      - PORT=5000
      - MYSQL_HOST=localhost
      - APPLICATION_NAME=example-backend
      - JWT_SECRET=supersecretpassword
      - CACHE_KEY=mystringpassword
      - SWAGGER_DOC=swaggerDEV
    
    ports:
      - "5000:5000"
  
  mysql:
    image: mysql